# new app heh
# Abstract generator
library(shiny)
library(tidyverse)
library(ggfittext)


stonk_fun <- function(){
  
  nouns = c("beans", "tacos")
  points = c("ding", "dong")
  authors = c(paste("Smith et al.", sample(1960:2020, 1)), 
              paste("Jones et al.", sample(1960:2020, 1)))
  
  Argue <- c(
  paste("Along similar lines,", sample(authors, 1), "argues that", sample(points, 1)),
  paste("There seems to be no compelling reason to argue that", sample(points, 1)), 
  paste("As a rebuttal to this point, it could be argued that", sample(points, 1)), 
  paste("There are", sample(c("two","three","four")), "main arguments that can be advanced to support", sample(points, 1)), 
  paste("The underlying argument ", sample(c("in favor of ", "against ")), sample(nouns,1), " is that ", sample(points, 1),sep = ""), 
  paste(sample(authors,1),"'s argument",sample(c("in favor of", "against")), sample(nouns,1), "runs as follows:", sample(points, 1), sep = " "))
  
  
  Claim <- c(
  paste("In this paper, I put forward the claim that", sample(points, 1)),
  paste(sample(authors,1), "develops the claim that", sample(points, 1)),
  paste("There is",sample(c("ample", "growing"),1), "support for the claim that", sample(points, 1)),
  paste(sample(authors,1), "findings lend support to the claim that", sample(points, 1)),
  paste("Taking a middle-ground position,", sample(authors,1), "claims that", sample(points, 1))
)
  
  Data <- c(
  paste("The data gathered in", sample(authors,1), "suggest that", sample(points,1)),
  paste("The data appears to suggest that", sample(points,1)),
  paste("The data yielded by this study provide convincing evidence that", sample(points,1)),
  paste("A closer look at the data indicates that", sample(points,1),"."),
  paste("The data generated by these experiments are reported in Table 1."),
  paste("The aim of this section is to generalize beyond the data and", sample(points,1),".")
  )
  
  Debate <- c(
  paste(sample(authors,1),"has encouraged debate on", sample(points,1)),
  paste("There has been an inconclusive debate about whether", sample(points,1)),
  paste("The question of whether", sample(points,1), "has caused much debate in our profession over the years"),
  paste("Much of the current debate revolves around", sample(points,1))
  )
  
  Discussion <- c(
  paste("In this", sample(c("section,","chapter,"),1),"the discussion will point to", sample(points,1)),
  paste("The foregoing discussion implies that",sample(points,1)),
  paste("For the sake of discussion, I would like to argue that ",sample(points,1),".", sep = ""),
  paste("In this study, the question under discussion is", sample(points,1)),
  paste("In this paper, the discussion centers on",sample(points,1)),
  paste("[X] lies at the heart of the discussion on ___.")
  )

  Evidence <- c(
  paste("The available evidence seems to suggest that", sample(points,1)),
  paste("On the basis of the evidence currently available, it seems fair to suggest that",sample(points,1)),
  paste("There is overwhelming evidence for the notion that",sample(points,1)),
  paste("Further evidence",sample(c("supporting","against"),1), sample(points,1), "may lie in the findings of", sample(authors,1),"who state,",sample(points,1)),
  paste("These results provide confirmatory evidence that", sample(points,1))
  )
  
  Ground <- c(
  paste("I will now summarize the ground covered in this chapter by",sample(points,1)),
  paste("On logical grounds, there is no compelling reason to argue that",sample(points,1)),
  paste(sample(authors,1),"takes a middle-ground position and argues that", sample(points,1)),
  paste("On these grounds, we can argue that",sample(points,1)),
  paste(sample(authors,1),"views are grounded on the assumption that",sample(points,1))
  )
  
  Issue <- c(
  paste("This study is an attempt to address the issue of",sample(points,1)),
  paste("In the present study, the issue under scrutiny is",sample(points,1)),
  paste("The issue of whether",sample(points,1), "is clouded by the fact that",sample(points,1)),
  paste("To portray the issue in", sample(authors,1), "’s terms,",sample(points,1)),
  paste("Given the centrality of this issue, I will now", sample(points,1)),
  paste("This chapter is concerned with the issue of how",sample(points,1))
  )
  Literature <- c(
  paste(sample(authors,1), "is prominent in the literature on", sample(points,1)),
  paste("There is a rapidly growing literature on [X], which indicates that", sample(points,1)),
  paste("The literature shows no consensus on",sample(points,1), "which means that",sample(points,1)),
  paste("The current literature on",sample(points,1),"abounds with examples of",sample(points,1))
  )
  
  # Resume work here
  Premise <- c( 
  a. The main theoretical premise behind [X] is that ___.
  b. [X] and [Y] share an important premise: ___.
  c. [X] is premised on the assumption that ___.
  d. The basic premises of [X]’s theory / argument are ___.
  e. The arguments against [X]’s premise rest on [four] assumptions: ___.
  )
  
  Research <- c(
  paste("This study draws on research conducted by",sample(points,1)),
  paste("Although there has been relatively little research on", sample(points,1)),
  paste("In the last", sample(c(1:10),1), "years, studies have provided ample support for the assertion that",sample(points,1)),
  paste("Current research appears / seems to validate the view that",sample(points,1)),
  paste("Research on / into ___ does not support the view that",sample(points,1)),
  paste("Further research in this area may include",sample(points,1)),
  paste("Evidence for", sample(points,1), "is borne out by research that shows",sample(points,1)),
  paste("There is insufficient research into",sample(points,1), "to draw any firm conclusions about", sample(points,1))
  )
  
  View <- c(
  "The consensus view seems to be that ___.",
  "[X] propounds the view that ___.",
  "Current research (does not) appear(s) to validate such a view.",
  "There have been dissenters to the view that ___.",
  "The answer to [X] / The difference between [X] and [Y] is not as clear-cut as popular views might suggest.",
  "The view that _____ is in line with [common sense].",
  "I am not alone in my view that ___.",
  "[X] puts forward the view that ___.",
  "[X]’s views rest on the assumption that ___."
  )
  
  
  comment = paste(  
    sample(lead_list, 1),
    sample(turn_list, 1),
    sample(quip_list, 1), sep = "")
  
  return(comment)
  
}















